spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Java-GIS-enterprise-Application-with-AI
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/javagis
          jwk-set-uri: http://localhost:8080/auth/realms/javagis/protocol/openid-connect/certs

server:
  port: 8081

  servlet:
    context-path: /api

# AWS Configuration
aws:
  region: eu-central-1
  credentials:
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}
  s3:
    bucket: ${AWS_S3_BUCKET:Java-GIS-enterprise-Application-with-AI-assets}

# Application specific properties
javagis:
  security:
    jwt:
      secret-key: ${JWT_SECRET:jwt_secretkey}
      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds
  stac:
    catalog-id: javagis-geospatial-catalog
    default-collection-id: environmental-monitoring
  ai:
    models-path: ${AI_MODELS_PATH:models}
    default-model: environmental-anomaly-detection
    workflow:
      cron:
        enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    com.basf.javagis: DEBUG
    org.hibernate.SQL: INFO
    org.springframework.web: INFO

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  info:
    git:
      mode: full

# OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.adeprogramming.javagis.controller

